name: beta

on:
  workflow_dispatch:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "${{ secrets.AWS_ASSUME_ROLE }}"
          aws-region: "us-east-1"
      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
      - name: Setup Buildx Remote Docker
        id: buildx
        uses: truemark/aws-buildx-remote-docker-instance-action@v4
        with:
          security-group-id: "${{ vars.SECURITY_GROUP_ID }}"
          subnet-id: "${{ vars.SUBNET_ID }}"
          instance-profile: "${{ vars.INSTANCE_PROFILE }}"
          region: "us-east-2"
      - name: Build Amazon Linux
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            -f amazonlinux.Dockerfile \
            -t truemark/aws-cdk:beta-amazonlinux-${{github.run_number}} \
            -t truemark/aws-cdk:beta-amazonlinux \
            -t truemark/aws-cdk:beta \
            --target base \
            .
      - name: Copy beta-amazonlinux-${{github.run_number}} to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/aws-cdk:beta-amazonlinux-${{github.run_number}}"
          dest-image: "docker://public.ecr.aws/truemark/aws-cdk:beta-amazonlinux-${{github.run_number}}"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Copy beta-amazonlinux to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/aws-cdk:beta-amazonlinux"
          dest-image: "docker://public.ecr.aws/truemark/aws-cdk:beta-amazonlinux"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Copy beta to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/aws-cdk:beta"
          dest-image: "docker://public.ecr.aws/truemark/aws-cdk:beta"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Build Amazon Linux Dotnet 6
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            -f amazonlinux.Dockerfile \
            -t truemark/aws-cdk:beta-amazonlinux-dotnet6-${{github.run_number}} \
            -t truemark/aws-cdk:beta-amazonlinux-dotnet6 \
            -t truemark/aws-cdk:beta-dotnet6 \
            --target dotnet6 \
            .
      - name: Copy beta-amazonlinux-dotnet6-${{github.run_number}} to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/aws-cdk:beta-amazonlinux-dotnet6-${{github.run_number}}"
          dest-image: "docker://public.ecr.aws/truemark/aws-cdk:beta-amazonlinux-dotnet6-${{github.run_number}}"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Copy beta-amazonlinux-dotnet6 to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/aws-cdk:beta-amazonlinux-dotnet6"
          dest-image: "docker://public.ecr.aws/truemark/aws-cdk:beta-amazonlinux-dotnet6"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Copy beta-dotnet6 to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/aws-cdk:beta-dotnet6"
          dest-image: "docker://public.ecr.aws/truemark/aws-cdk:beta-dotnet6"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Build Alpine
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            -f alpine.Dockerfile \
            -t truemark/aws-cdk:beta-alpine-${{github.run_number}} \
            -t truemark/aws-cdk:beta-alpine \
            --target base \
            .
      - name: Copy beta-alpine-${{github.run_number}} to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/aws-cdk:beta-alpine-${{github.run_number}}"
          dest-image: "docker://public.ecr.aws/truemark/aws-cdk:beta-alpine-${{github.run_number}}"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Copy beta-alpine to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/aws-cdk:beta-alpine"
          dest-image: "docker://public.ecr.aws/truemark/aws-cdk:beta-alpine"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Build Alpine Dotnet 6
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            -f alpine.Dockerfile \
            -t truemark/aws-cdk:beta-alpine-dotnet6-${{github.run_number}} \
            -t truemark/aws-cdk:beta-alpine-dotnet6 \
            --target dotnet6 \
            .
      - name: Copy beta-alpine-dotnet6-${{github.run_number}} to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/aws-cdk:beta-alpine-dotnet6-${{github.run_number}}"
          dest-image: "docker://public.ecr.aws/truemark/aws-cdk:beta-alpine-dotnet6-${{github.run_number}}"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Copy beta-alpine-dotnet6 to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/aws-cdk:beta-alpine-dotnet6"
          dest-image: "docker://public.ecr.aws/truemark/aws-cdk:beta-alpine-dotnet6"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Build Ubuntu
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            -f ubuntu.Dockerfile \
            -t truemark/aws-cdk:beta-ubuntu-${{github.run_number}} \
            -t truemark/aws-cdk:beta-ubuntu \
            --target base \
            .
      - name: Copy beta-ubuntu-${{github.run_number}} to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/aws-cdk:beta-ubuntu-${{github.run_number}}"
          dest-image: "docker://public.ecr.aws/truemark/aws-cdk:beta-ubuntu-${{github.run_number}}"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Copy beta-ubuntu to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/aws-cdk:beta-ubuntu"
          dest-image: "docker://public.ecr.aws/truemark/aws-cdk:beta-ubuntu"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Build Ubuntu Dotnet 6
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            -f ubuntu.Dockerfile \
            -t truemark/aws-cdk:beta-ubuntu-dotnet6-${{github.run_number}} \
            -t truemark/aws-cdk:beta-ubuntu-dotnet6 \
            --target dotnet6 \
            .
      - name: Copy beta-ubuntu-dotnet6-${{github.run_number}} to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/aws-cdk:beta-ubuntu-dotnet6-${{github.run_number}}"
          dest-image: "docker://public.ecr.aws/truemark/aws-cdk:beta-ubuntu-dotnet6-${{github.run_number}}"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Copy beta-ubuntu-dotnet6 to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/aws-cdk:beta-ubuntu-dotnet6"
          dest-image: "docker://public.ecr.aws/truemark/aws-cdk:beta-ubuntu-dotnet6"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
