name: example

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "${{ secrets.AWS_ASSUME_ROLE }}"
          aws-region: "us-east-2"
      - name: Setup ARM64 EC2
        id: ec2-arm64
        uses: truemark/aws-ec2-run-instance-action@ac6a10c11e1997ed826f5f058be9ad60cace464e
        with:
          security-group-id: "sg-0baf5bcfe9f21efa5"
          subnet-id: "subnet-09a35a2abd797dbf9"
          image-id: "default-arm64"
          instance-type: "c7g.large"
          instance-profile: "TruemarkEC2RoleforSSM"
          region: "us-east-2"
      - name: Wait for EC2
        id: ec2-wait
        uses: truemark/aws-ec2-wait-action@870b81625c8af9957e6d91f5fb7df2114794bbb2
        with:
          instance-ids: ${{ steps.ec2-arm64.outputs.instance-id }}
          region: "us-east-2"

#      - name: Get the output time
#        run: echo "The time was ${{ steps.hello.outputs.time }}"
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#        with:
#          platforms: all
#      - name: Set up Docker Buildx
#        id: buildx
#        uses: docker/setup-buildx-action@v2
#      - name: Build
#        run: |
#          docker buildx build \
#            --push \
#            --platform linux/arm64,linux/amd64 \
#            -f amazonlinux.Dockerfile \
#            -t truemark/aws-cdk:beta-amazonlinux-${{github.run_number}} \
#            -t truemark/aws-cdk:beta-amazonlinux \
#            -t truemark/aws-cdk:beta \
#            .
#          docker buildx build \
#            --push \
#            --platform linux/arm64,linux/amd64 \
#            -f alpine.Dockerfile \
#            -t truemark/aws-cdk:beta-alpine-${{github.run_number}} \
#            -t truemark/aws-cdk:beta-alpine \
#            .
#          docker buildx build \
#            --push \
#            --platform linux/arm64,linux/amd64 \
#            -f ubuntu.Dockerfile \
#            -t truemark/aws-cdk:beta-ubuntu-${{github.run_number}} \
#            -t truemark/aws-cdk:beta-ubuntu \
#            .
