name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # Run at 4PM UTC every Monday
    - cron: '0 16 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            -f amazonlinux.Dockerfile \
            -t truemark/aws-cdk:amazonlinux-${{github.run_number}} \
            -t truemark/aws-cdk:amazonlinux \
            -t truemark/aws-cdk:latest \
            .
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            -f alpine.Dockerfile \
            -t truemark/aws-cdk:alpine-${{github.run_number}} \
            -t truemark/aws-cdk:alpine \
            .
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            -f ubuntu.Dockerfile \
            -t truemark/aws-cdk:ubuntu-${{github.run_number}} \
            -t truemark/aws-cdk:ubuntu \
            .
      - name: Keepalive
        uses: gautamkrishnar/keepalive-workflow@v1
